### ISSUE TITLE
List of strings not supported in api.get_states()?

### ISSUE THREAD

**Issue by sbisca** [openskynetwork/opensky-api#3]
I want to use the function

`get_states(time_secs=0, icao24=None, serials=None)`

On the docs i saw that:

> Returns: OpenSkyStates if request was successful, None otherwise

This is my code that actually does't work (The fuction returns None)

```
def get_flights():
  s = api.get_states()
  flights = []
  j = 0
  # I want just 5 best results of the first 10 elements returned with **api.get_states()**
  for i in range(10):
          tmp = s.states[i]
          if tmp.icao24 != "" and tmp.latitude != "" and tmp.longitude != "" and j < 5:
              flights.append(tmp.icao24)
              j += 1
  return flights

flights = get_flights()
s = api.get_states(icao24=flights)
```

and actually this code works

```
flights = ['43ea96', 'aa8477', 'aa56da', 'a3e917', 'a52911']
s = api.get_states(icao24=flights)

print(s)
```

How can i pass a list of "icao24" dinamically?

**Comment by fixje** [comment]
The API will also return None if you exceed the rate limit as given in the following table.

Time to wait between subsequent requests:

|                            | get_states() | get_own_states() |
| ------------------------| ---------------- | ------------------------ |
| **unregistered user** | 10s | -- |
| **registered user** | 5s | 1s |

In the first code snippet you issue two consecutive requests within a very short time, so the second one, `api.get_states(icao24=flights)` will return `None`.

I agree that this behavior is not very user-friendly, but it turned out to be useful as otherwise we would be flooded with requests. Thanks for your feedback. We will think about a more user-friendly solution.
_Note_: The server will also enforce this rate limit and just return the same values as before ;)

A working (and more efficient) solution would be to filter the data locally for the first request and then re-use the list of ICAO addresses:
```
from time import sleep
api = OpenSkyApi()
resp = api.get_states()
if resp is not None and resp.states is not None:
    flights = [s for s in resp.states[:10] if s.latitude is not None][:5]
    icaos = [s.icao24 for s in flights]
    print(icaos)
    while True:
        print(flights, len(flights))
        sleep(10)
        resp = api.get_states(icao24=icaos)
        flights = resp.states if resp is not None else []
```
